# Generated by Django 2.0 on 2018-08-18 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('vin', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=80)),
                ('car_model', models.CharField(max_length=80)),
                ('year', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('trim', models.CharField(max_length=80)),
                ('engine', models.CharField(max_length=80)),
                ('body', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=80)),
                ('transmission', models.CharField(max_length=80)),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Dealer')),
            ],
        ),
    ]
