# Generated by Django 2.0 on 2018-08-23 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDealer',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.BigIntegerField()),
                ('car_dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealer.Dealer')),
            ],
        ),
    ]
