# Generated by Django 2.0 on 2018-08-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('pwd', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('join_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
