# Generated by Django 2.0 on 2018-08-21 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastSearch',
            fields=[
                ('auto_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=50)),
                ('location_lng', models.FloatField()),
                ('loaction_lat', models.FloatField()),
                ('car_make', models.CharField(max_length=30)),
                ('max_distance', models.IntegerField()),
                ('search_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
