# Generated by Django 2.0 on 2018-08-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180821_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastsearch',
            name='max_distance',
            field=models.IntegerField(null=True),
        ),
    ]
