# Generated by Django 2.0 on 2018-08-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180821_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastsearch',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
