# Generated by Django 2.0 on 2018-08-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_pastsearch_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastsearch',
            name='location_name',
            field=models.CharField(max_length=100),
        ),
    ]
